[package]
name = "obj_detection"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28.0"
nokhwa = {version = "0.10.9", features = ["input-native"]}
image = "0.25"
ndarray = "0.15"
ort = "2"                 # ONNX Runtime (CPU)
anyhow = "1"